language: generic

install:
  - openssl aes-256-cbc -K $encrypted_34612acf6c90_key -iv $encrypted_34612acf6c90_iv -in .travis_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name conao3
  - git config --global user.email conao3@gmail.com

  - git remote -v
  - git remote set-url origin git@github.com:conao3/files.git

  - docker pull conao3/imagick:7.0.8
  - docker pull conao3/imagick-roboto:1.0.0
  - docker pull conao3/mustache:1.1.0

script:
  - make checkout
  - touch blob/headers/png/*
  - make commit && make merge
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then make push; fi
